name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository        # Usando o template de repositório
          filename: metrics.repository.svg  # Nome do arquivo de saída (SVG)
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          user: bhza                  # Seu usuário do GitHub
          repo: metrics               # Nome do repositório
          plugin_lines: yes           # Ativa o plugin para linhas
          plugin_followup: yes        # Ativa o plugin de follow-up
          plugin_projects: yes        # Ativa o plugin de projetos
          plugin_projects_repositories: bhza/metrics/projects/1  # Especifica o repositório do projeto
